server:
  port: 8084
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
eureka:
  instance:
    hostname: localhost